name: checks

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Test
        run: |
          docker-compose build
          docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      # - name: Lint
      #   run: docker-compose run --rm app sh -c "flake8"
